language: generic

dist: trusty

services:
- docker

env:
  matrix:
  - PRODUCT_TESTS='multinode -x quarantine,big_query,storage_formats,profile_specific_tests'
  - PRODUCT_TESTS='singlenode-kerberos-hdfs-impersonation -g storage_formats,cli,hdfs_impersonation,authorization'

# The whole section is reserved for overriding by cron-ed API calls.
# Partial overrides are impossible. See https://docs.travis-ci.com/user/triggering-builds.
before_install:
 - export ARTIFACTS_S3_BUCKET='ARTIFACTS_S3_BUCKET_WILL_BE_OVERRIDEN'
 - export ARTIFACTS_S3_PATH='ARTIFACTS_S3_PATH_WILL_BE_OVERRIDEN'
 - export PRESTO_BRANCH='BRANCH_WILL_BE_OVERRIDEN'
 - export PRESTO_BUILD='BUILD_WILL_BE_OVERRIDEN'

install:
- sudo pip install awscli
- |
  aws s3 sync s3://${ARTIFACTS_S3_BUCKET}/${ARTIFACTS_S3_PATH}/${PRESTO_BRANCH}/${PRESTO_BUILD} /tmp/artifacts \
    --exclude '*' \
    --include 'git-revision.txt' \
    --include 'presto-server-*.tar.gz' \
    --include 'presto-cli-*-executable.jar' \
    --include 'presto-product-tests-*-executable.jar' \
    --no-sign-request
- git clone --depth=50 --branch=${PRESTO_BRANCH} https://github.com/Teradata/presto.git
- cd presto
- git checkout `cat /tmp/artifacts/git-revision.txt`
- tar -xf /tmp/artifacts/presto-server-*.tar.gz -C /tmp/

script: |
  export HADOOP_MASTER_IMAGE='teradatalabs/hdp2.3-master:6'
  export PRESTO_SERVER_DIR=/tmp/presto-server-*
  export PRESTO_CLI_JAR=/tmp/artifacts/presto-cli-*-executable.jar
  export PRODUCT_TESTS_JAR=/tmp/artifacts/presto-product-tests-*-executable.jar
  ./presto-product-tests/bin/run_on_docker.sh $PRODUCT_TESTS

after_script:
- |
  if [[ -v S3_ACCESS_KEY ]]; then
    export AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
    export AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
    mkdir /tmp/links
    JOB_STATUS=`[ "$TRAVIS_TEST_RESULT" == "0" ] && echo SUCCESS || echo FAILURE`
    echo "<script>location='https://travis-ci.org/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_BUILD_ID}'</script>" \
      > /tmp/links/${TRAVIS_BUILD_NUMBER}.html
    echo "<script>location='https://travis-ci.org/${TRAVIS_REPO_SLUG}/jobs/${TRAVIS_JOB_ID}'</script>" \
      > /tmp/links/${TRAVIS_JOB_NUMBER}_${JOB_STATUS}.html
    aws s3 sync /tmp/links \
      s3://${ARTIFACTS_S3_BUCKET}/${ARTIFACTS_S3_PATH}/${PRESTO_BRANCH}/${PRESTO_BUILD}/travis_checks
  fi
